require 'jarvis/services/null_service'
require 'jarvis/services/dice'
require 'jarvis/services/eightball'
require 'jarvis/services/fact'
require 'jarvis/services/giphy'
require 'jarvis/services/i_heart_quotes'
